config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users
  resources :recruitments, except: :index do
    collection do
      get 'merit'
    end
    resources :orders, only: [:index, :new, :create, :show], controller: 'orders'
  end
  root to: "recruitments#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :order
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveHash::Base
  self.data = [
    {id: 0, name: 'エリア'}, {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, 
    {id: 3, name: '岩手県'}, {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, 
    {id: 6, name: '山形県'}, {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, 
    {id: 9, name: '栃木県'}, {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, 
    {id: 12, name: '千葉県'}, {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, 
    {id: 15, name: '新潟県'}, {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, 
    {id: 18, name: '福井県'}, {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, 
    {id: 21, name: '岐阜県'}, {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, 
    {id: 24, name: '三重県'}, {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, 
    {id: 27, name: '大阪府'}, {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, 
    {id: 30, name: '和歌山県'}, {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, 
    {id: 33, name: '岡山県'}, {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, 
    {id: 36, name: '徳島県'}, {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, 
    {id: 39, name: '高知県'}, {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, 
    {id: 42, name: '長崎県'}, {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, 
    {id: 45, name: '宮崎県'}, {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
  end

app/models/genre.rb
class Genre < ActiveHash::Base

  self.data = [
    { id: 0, name: '求人ジャンル' },
    { id: 1, name: 'キッチン' },
    { id: 2, name: 'ホール' },
  ]
end

app/models/hole.rb
class Hole < ActiveHash::Base
  self.data = [
    { id: 1, name: 'ホール経験' },   
    { id: 2, name: '未経験' },
    { id: 3, name: '1〜3年' },
    { id: 4, name: '4〜10年' },
    { id: 5, name: '10年以上' },
  ]
end

app/models/kitchen.rb
class Kitchen < ActiveHash::Base

  self.data = [
    { id: 1, name: '調理経験' },
    { id: 2, name: '未経験' },
    { id: 3, name: '1〜3年' },
    { id: 4, name: '4〜10年' },
    { id: 5, name: '10年以上' },
  ]
end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to  :recruitment 
  has_one     :address
  belongs_to  :user

end

app/models/order_address.rb
class OrderAddress
  include ActiveModel::Model
  attr_accessor :postal_code, :area_id, :city, :house_number, :building_name, :phone_number, :user_id, :recruitment_id

  with_options presence: true do
    validates :postal_code,  format: { with: /\A[0-9]{3}-[0-9]{4}\z/, message: "is invalid. Include hyphen(-)" }
    validates :city 
    validates :house_number
    validates :phone_number, format: { with: /\A[0-9]{11}+\z/i, message: "is invalid. Input half-width characters."}
  end
  validates :area_id, numericality: { other_than: 0, message: "can't be blank" }

  def save
   order = Order.create(recruitment_id: recruitment_id, user_id: user_id)
   Address.create(postal_code: postal_code, area_id: area_id, city: city, house_number: house_number, building_name: building_name, phone_number: phone_number, order_id: order.id)
    
   
  end
end

app/models/recruitment.rb
class Recruitment < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to        :user
  has_one_attached  :image
  has_one :order

  belongs_to_active_hash :genre, shortcuts: [:name]
  belongs_to_active_hash :area,  shortcuts: [:name]

  validates :genre_id,  numericality: { other_than: 0 } 
  validates :area_id,     numericality: { other_than: 0 }

  with_options presence: true do
   validates :image
   validates :name
   validates :info
   validates :date
   validates :area_id
   validates :genre_id
   validates :salary
   validates :time_start
   validates :time_finish
   validates :station
   validates :phone
   validates :place
  end
end

app/models/sex.rb
class Sex < ActiveHash::Base
  self.data = [
    { id: 0, name: '性別' },
    { id: 1, name: '男' },
    { id: 2, name: '女' },
  ]
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_many    :recruitments
  has_many    :orders
  belongs_to_active_hash :kitchen, shortcuts: [:name]
  belongs_to_active_hash :hole,    shortcuts: [:name]
  belongs_to_active_hash :sex,     shortcuts: [:name]

  validates :kitchen_id,  numericality: { other_than: 0 } 
  validates :hole_id,     numericality: { other_than: 0 } 
  validates :sex_id,     numericality: { other_than: 0 } 


  with_options presence: true do
    validates :nickname

    PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
    validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください' 
  end
  
  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/, message: '全角文字を使用してください' } do
    validates :last_name
    validates :first_name
  end

  with_options presence: true, format: { with: /\A[ァ-ン]+\z/, message: 'カナを使用してください' } do
    validates :last_name_kana
    validates :first_name_kana
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :last_name, :first_name, :last_name_kana, :first_name_kana, :sex_id, :age, :kitchen_id, :hole_id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item,only: [:new, :create]

  def index
  end

  def new
    redirect_to root_path if current_user == @recruitment.user
    @order_address = OrderAddress.new
    
    # order = current_user.orders.build
    # @address = order.build_address
  end

  def create
    @order_address = OrderAddress.new(order_params)
    if @order_address.valid?
       @order_address.save
       return redirect_to root_path
    else
      render action: :new
    end
  end  

  def show
  end

  private

  def order_params
    params.permit(:postal_code, :area_id, :city, :house_number, :building_name, :phone_number, :order_id, :recruitment_id).merge(user_id: current_user.id)
  end

  def set_item
    @recruitment = Recruitment.find(params[:recruitment_id])
  end
end

app/controllers/recruitments_controller.rb
class RecruitmentsController < ApplicationController
  before_action :authenticate_user!,only: [:new, :edit]
  before_action :set_item,only: [:show, :edit, :update, :destroy ]

  def index
    @recruitments = Recruitment.all
  end

  def new
    @recruitment = current_user.recruitments.build
    if @recruitment.save
      redirect_to root_path
    else
      render :new
    end  
  end

  def create
    @recruitment = current_user.recruitments.build(recruitment_params)
    if @recruitment.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
    redirect_to new_user_session_path unless user_signed_in? && current_user.id == @recruitment.user_id
  end


  def update
    if @recruitment.update(recruitment_params)
      redirect_to recruitment_path(@recruitment.id)
    else
      render :edit
    end
  end 

  def destroy
    
    redirect_to root_path if current_user.id != @recruitment.user_id
    @recruitment.destroy
    redirect_to root_path
  end

  def merit
  end



  private

  def set_item
    @recruitment = Recruitment.find(params[:id])
  end

  def recruitment_params
    params.require(:recruitment).permit([
      :name,
      :date,
      :info, 
      :area_id, 
      :salary, 
      :time_start, 
      :time_finish, 
      :station, 
      :phone, 
      :genre_id, 
      :image, 
      :place
    ])
  end  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @applied_jobs = current_user.orders.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/recruitments_helper.rb
module RecruitmentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="items-sell-footer <%= 'no-bg' if controller_name == 'recruitments' %>">
  <ul class="menu">
    <li><a href="#">プライバシーポリシー</a></li>
    <li><a href="#">利用規約</a></li>
    <li><a href="#">特定商取引に関する表記</a></li>
  </ul>
  <%= link_to image_tag('logo.png' , size: '185x50'), "/" %>
  <p class="inc">
    ©︎Chitty×2 Bang×2
  </p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Chitty×2 Bang×2</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_pack_tag 'application' %>
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@200;300;400;500&display=swap" rel="stylesheet">
</head>

<body>
  <%# <%= render "shared/header" if controller_name == 'users' %>
  <%= yield %>
</body>

</html>

app/views/orders/index.html.erb
<%= render "shared/second-header"%>

<div class='transaction-contents'>
  <div class='transaction-main'>
    <h1 class='transaction-title-text'>
      購入内容の確認
    </h1>
    <%# 購入内容の表示 %>
    <div class='buy-item-info'>
      <%= image_tag "item-sample.png", class: 'buy-item-img' %>
      <div class='buy-item-right-content'>
        <h2 class='buy-item-text'>
          <%= "商品名" %>
        </h2>
        <div class='buy-item-price'>
          <p class='item-price-text'>¥<%= 999,999,999 %></p>
          <p class='item-price-sub-text'><%= '配送料負担' %></p>
        </div>
      </div>
    </div>
    <%# /購入内容の表示 %>

    <%# 支払額の表示 %>
    <div class='item-payment'>
      <h1 class='item-payment-title'>
        支払金額
      </h1>
      <p class='item-payment-price'>
        ¥<%= "販売価格" %>
      </p>
    </div>
    <%# /支払額の表示 %>

    <%= form_with id: 'charge-form', class: 'transaction-form-wrap',local: true do |f| %>
    <%# カード情報の入力 %>
    <div class='credit-card-form'>
      <h1 class='info-input-haedline'>
        クレジットカード情報入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">カード情報</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field 'hoge', class:"input-default", id:"card-number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
        <div class='available-card'>
          <%= image_tag 'card-visa.gif', class: 'card-logo'%>
          <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
          <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
          <%= image_tag 'card-amex.gif', class: 'card-logo'%>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">有効期限</label>
          <span class="indispensable">必須</span>
        </div>
        <div class='input-expiration-date-wrap'>
          <%= f.text_area 'hoge', class:"input-expiration-date", id:"card-exp-month", placeholder:"例)3" %>
          <p>月</p>
          <%= f.text_area 'hoge', class:"input-expiration-date", id:"card-exp-year", placeholder:"例)23" %>
          <p>年</p>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">セキュリティコード</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field "hoge",class:"input-default", id:"card-cvc", placeholder:"カード背面4桁もしくは3桁の番号", maxlength:"4" %>
      </div>
    </div>
    <%# /カード情報の入力 %>
    
    <%# 配送先の入力 %>
    <div class='shipping-address-form'>
      <h1 class='info-input-haedline'>
        配送先入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">郵便番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field 'hoge', class:"input-default", id:"postal-code", placeholder:"例）123-4567", maxlength:"8" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">都道府県</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"prefecture"}) %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">市区町村</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field 'hoge', class:"input-default", id:"city", placeholder:"例）横浜市緑区"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">番地</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field 'hoge', class:"input-default", id:"addresses", placeholder:"例）青山1-1-1"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">建物名</label>
          <span class="form-any">任意</span>
        </div>
        <%= f.text_field 'hoge', class:"input-default", id:"building", placeholder:"例）柳ビル103"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">電話番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field 'hoge', class:"input-default", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
      </div>
    </div>
    <%# /配送先の入力 %>
    <div class='buy-btn'>
      <%= f.submit "購入" ,class:"buy-red-btn" %>
    </div>
    <% end %>
  </div>
</div>
<%= render "shared/second-footer"%>

app/views/orders/new.html.erb
<%= render "shared/second-header"%>

<div class='transaction-contents'>
  <div class='transaction-main'>
    <h1 class='transaction-title-text'>
      応募内容の確認
    </h1>
    <%# 購入内容の表示 %>
    <div class='buy-item-info'>
      <%= image_tag @recruitment.image, class: 'buy-item-img' %>
      <div class='buy-item-right-content'>
        <h2 class='buy-item-text'>
          <%= @recruitment.name %>
        </h2>
        <div class='buy-item-price'>
          <p class='item-price-text'>日付 </p>
          <p class='item-price-sub-text'><%= @recruitment.date %></p>
        </div>
      </div>
    </div>
    <%# /購入内容の表示 %>

    <%# 支払額の表示 %>
    <div class='item-payment'>
      <h1 class='item-payment-title'>
        労働時間
      </h1>
      <p class='item-payment-price'>
        <%= @recruitment.time_start %>~
        <%= @recruitment.time_finish %>
      </p>
    </div>
    <%# /支払額の表示 %>

    <%= form_with model: @address, url: recruitment_orders_path, id: 'charge-form', class: 'transaction-form-wrap',local: true do |f| %>
    
    <%# 配送先の入力 %>
    <div class='shipping-address-form'>
      <h1 class='info-input-haedline'>
        配送先入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">郵便番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :postal_code, class:"input-default", id:"postal-code", placeholder:"例）123-4567", maxlength:"8" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">都道府県</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-box", id:"prefecture"}) %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">市区町村</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :city, class:"input-default", id:"city", placeholder:"例）横浜市緑区"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">番地</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :house_number, class:"input-default", id:"addresses", placeholder:"例）青山1-1-1"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">建物名</label>
          <span class="form-any">任意</span>
        </div>
        <%= f.text_field :building_name, class:"input-default", id:"building", placeholder:"例）柳ビル103"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">電話番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :phone_number, class:"input-default", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
      </div>
    </div>
    <%# /配送先の入力 %> 
    <div class='buy-btn'>
      <%= f.submit "購入" ,class:"buy-red-btn" %>
    </div>
    <% end %>
  </div>
</div>
<%= render "shared/second-footer"%>

app/views/recruitments/_recruitment.html.erb
<li class="list">
  <%= link_to recruitment_path(recruitment) do %>
    <div class="item-img-content">
      <%= image_tag recruitment.image, class: 'item-img' %>
      <% if recruitment.order.present? %>
          <div class='sold-out'>
            <span>募集終了!!</span>
          </div>
      <% end %>
    </div>
    <div class="item-info">
      <h3 class="item-name">
        <%= recruitment.name %>
      </h3>
      <table class="recruitment-table">
				<tbody>
					<tr>
						<th>勤務地</th>
						<td>
							<p>
								<span class="location01"><%= recruitment.area_name %></span>
								<span class="location02">最寄り駅：<%= recruitment.station %></span>
							</p>
						</td>
					</tr>
					<tr>
						<th>日付</th>
						<td><%= recruitment.date %></td>
					</tr>
					<tr>
						<th>時給</th>
						<td><%= recruitment.salary %> 円</td>
					</tr>
					<tr>
						<th>勤務時間</th>
						<td>
								<%= recruitment.time_start %> ~ <%= recruitment.time_finish %>
						</td>
					</tr>
					<tr>
						<th>仕事内容</th>
						<td><%= recruitment.info[0, 30] %></td>
					</tr>
				</tbody>
			</table>

    </div>
  <% end %>      
</li>

app/views/recruitments/edit.html.erb
<div class="items-sell-contents">
  <%= render 'recruitments/shared/header'%>

  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>

    <%= form_with(model: @recruitment, local: true) do |f| %>
      <%= render 'recruitments/inputs/image',         f: f %>
      <%= render 'recruitments/inputs/item',          f: f %>
      <%= render 'recruitments/inputs/item_detail',   f: f %>
      <%= render 'recruitments/inputs/store_details', f: f %>
      <%= render 'recruitments/inputs/submit_btn',    f: f %>
    <% end %>
  </div>

  <%= render 'layouts/footer' %>
</div>

app/views/recruitments/index.html.erb
<%= render "shared/header" %>
<div class='main'>

 
  <div class='title-contents'>
    <div class='first-view-text'>
      <p class='first-view-title'>時間を自由に使いたい</p>
      <p class='first-view-title'>その想いを、私達がサポート致します。</p>
    </div>
    <div class='first-view'>
      <div class='first-view-image'></div>
    </div>
  </div>


  

  <%# お仕事をお探しの方 %>
  <div class='feature-contents'>
    <ul class='feature-lists'>
      <li class='list'>
        <%= link_to root_path do %>
        <%= image_tag "search.jpg", class:"list-pict" %>
        <% end %>
        <h3 class='feature-list-text'>
          お仕事をお探しの方
        </h3>
        <p class='feature-list-description'>
          豊富な飲食専門の求人データベースの中からあなたの希望・夢・目標・転職ペースに合わせてオンリーワンの仕事を自ら選べます。
        </p>
      </li>
      <li class='list'>
        <%= link_to new_recruitment_path do %>
        <%= image_tag "cooking.jpg", class:"list-pict" %>
        <% end %>
        <h3 class='feature-list-text'>
          人材をお探しの方
        </h3>
        <p class='feature-list-description'>
          「人」「時間」「コスト」多様化する人事課題に対し、
          オンライン上で人材探しがおこなえる。
        </p>
      </li>
      <li class='list'>
        <%= link_to new_recruitment_path do %>
        <%= image_tag "easy.jpg", class:"list-pict" %>
        <% end %>
        <h3 class='feature-list-text'>
          簡単に募集開始
        </h3>
        <p class='feature-list-description'>
          ログインID・PW発行後に、求人募集にてテンプレートを作成し、募集情報 日時・報酬を入力すれば、すぐアプリに掲載されます。
        </p>
      </li>
    </ul>
  </div>
  <%# /お仕事をお探しの方 %>
  
  <div class='ad-contents' style="background-image: url(<%= asset_path 'shake-hands.jpg'%>)">  
    <h2 class='ad-title'>
      お客様のベストパートナーでありたい
    </h2>
    <p class='ad-explain'>
      私たちは飲食業界において難しい人材確保をなされている個人店舗、
    </p>
    <p class='ad-explain'>
      企業の方々や
      希望・夢・目標をもってお仕事を探されている人々の
    </p>
    <p class='ad-explain'>
      ベストパートナーでありたいと考えております。
    </p>
  </div>

  <div class='item-contents'>
    <h2 class='title'>求人一覧</h2>
    <ul class="item-lists">
      <%= render partial: 'recruitment', collection: @recruitments %>
    </ul>
  </div>
</div>
<%= render "shared/footer" %>

app/views/recruitments/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @recruitment.name %>
    </h2>
    <div class='item-img-content'>
      <%= image_tag @recruitment.image ,class:"item-box-img" %>
      <% if @recruitment.order.present? %>
          <div class='sold-out'>
            <span>募集終了!!</span>
          </div>
      <% end %>
    </div>
    <div class="item-price-box">
      <span class="item-price">
        <%= '時給'%><%= @recruitment.salary%>円
      </span>
      <span class="item-price">
        <%= '日付' %>
        <%= @recruitment.date %>
      </span>
    </div>

    <%# ログインしているユーザーと出品しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>
     <% if user_signed_in? && current_user == @recruitment.user %>
      <%= link_to '求人の編集', edit_recruitment_path(@recruitment), class: "item-red-btn" %>
      <p class='or-text'>or</p>
      <%= link_to '削除', recruitment_path(@recruitment), method: :delete, class:'item-destroy' %>
      <% else %>
      <%# 商品が売れていない場合はこちらを表示しましょう %>
      <%# <%= link_to '応募画面に進む', "#" ,class:"item-red-btn"%>

      <% unless @recruitment.order.present? %>
        <div class="favorite-btn">
          <%= link_to new_recruitment_order_path(@recruitment.id) do %>
            <span>応募画面に進む</span>
          <% end %>
        </div>
        <%# //商品が売れていない場合はこちらを表示しましょう %>
      <% end %>
     <% end %>

    <%# //ログインしているユーザーと出品しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>

    <div class="item-explain-box">
      <span><%= "求人説明" %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">店名</th>
          <td class="detail-value"><%= @recruitment.name %></td>
        </tr>
        <tr>
          <th class="detail-item">日付</th>
          <td class="detail-value"><%= @recruitment.date %></td>
        </tr><tr>
        <tr>
          <th class="detail-item">ジャンル</th>
          <td class="detail-value"><%= @recruitment.genre.name %></td>
        </tr>
        <tr>
          <th class="detail-item">給料</th>
          <td class="detail-value"><%= @recruitment.salary %>円</td>
        </tr>
        <tr>
          <th class="detail-item">勤務地</th>
          <td class="detail-value"><%= @recruitment.place %></td>
        </tr>
        <tr>
          <th class="detail-item">最寄り駅</th>
          <td class="detail-value"><%= @recruitment.station %></td>
        </tr>
        <tr>
          <th class="detail-item">電話番号</th>
          <td class="detail-value"><%= @recruitment.phone %></td>
        </tr>
        <tr>
          <td colspan='2' class='detail-value'>
            <%= @recruitment.info %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <%# /商品の概要 %>

</div>

<%= render "shared/footer" %>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class="header">
  <div class="nav">
    <div class="nav_left">
      <%= link_to image_tag("logo1white.png", class: :logo), root_path %>
    </div>
    <% if user_signed_in? %>
        <div class="nav_right"> 
          <%= link_to "メリット", merit_recruitments_path, class: :nav_btn %>
          <%= link_to "お仕事をお探しの方", root_path, class: :nav_btn %>
          <%= link_to "人材をお探しの方", new_recruitment_path, class: :nav_btn %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav_btn %>
          <%= link_to "my page", users_index_path, class: :nav_btn %>
        </div> 
    <% else %>
      <div class="nav_right">
        <%= link_to "メリット", merit_recruitments_path, class: :nav_btn %>
        <%= link_to "お仕事をお探しの方", root_path, class: :nav_btn %>
        <%= link_to "人材をお探しの方", new_recruitment_path, class: :nav_btn %>
        <%= link_to "ログイン", new_user_session_path, class: :nav_btn %>
        <%= link_to "新規登録", new_user_registration_path, class: :nav_btn %>
      </div>
    <% end %>
  </div>
</header>